language: python
python:
  - "3.9"
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - pip install tox
script:
  - tox
  - docker build -t ${DOCKER_REPO} .
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=linting
deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: base
notifications:
  email: false
